import type { VoiceMetadata } from '../types/tts'

// 风格的中文映射字典
export const STYLE_NAME_MAP: Record<string, string> = {
  'advertisement-upbeat': '欢快广告',
  'affectionate': '撒娇/深情',
  'angry': '生气愤怒',
  'anxious': '焦虑紧张',
  'assistant': '智能助手',
  'calm': '沉着平静',
  'chat': '轻松聊天',
  'chat-casual': '日常闲聊',
  'cheerful': '愉快欢快',
  'customerservice': '客服服务',
  'customer-service': '客服服务',
  'disgruntled': '不满抱怨',
  'embarrassed': '害羞尴尬',
  'empathetic': '共情同理',
  'enthusiastic': '热情洋溢',
  'excited': '兴奋激动',
  'fearful': '恐惧害怕',
  'friendly': '亲切友好',
  'gentle': '温柔和蔼',
  'hopeful': '充满希望',
  'lyrical': '抒情诗意',
  'newscast': '专业播音',
  'newscast-casual': '轻松播报',
  'newscast-formal': '正式播报',
  'poetry-reading': '古诗朗诵',
  'sad': '悲伤忧郁',
  'serious': '严肃庄重',
  'shouting': '大声呐喊',
  'terrified': '极度恐慌',
  'unfriendly': '冷淡不友善',
  'whispering': '低语耳语',
  'documentary-narration': '纪录片旁白',
  'sports-commentary': '体育解说',
  'sports-commentary-excited': '激昂体育解说',
  'narration-relaxed': '舒缓讲述',
  'narration-professional': '专业解说',
  'story-telling': '故事讲述',
  'livecommercial': '直播带货',
  'live-commercial': '直播带货',
  'complaining': '抱怨诉苦',
  'sorry': '抱歉自责'
}

// 角色的中文映射字典
export const ROLE_NAME_MAP: Record<string, string> = {
  'Girl': '女孩',
  'Boy': '男孩',
  'YoungAdultFemale': '年轻女性',
  'YoungAdultMale': '年轻男性',
  'OlderAdultFemale': '年长女性',
  'OlderAdultMale': '年长男性',
  'SeniorFemale': '老年女性',
  'SeniorMale': '老年男性'
}

// 语言本地化名称字典
export const LOCALE_LABEL_MAP: Record<string, string> = {
  'zh-CN': '中文 (普通话, 简体)',
  'zh-HK': '中文 (粤语, 香港)',
  'zh-TW': '中文 (台湾普通话)',
  'en-US': '英语 (美国)',
  'en-GB': '英语 (英国)',
  'ja-JP': '日语 (日本)',
  'ko-KR': '韩语 (韩国)',
  'fr-FR': '法语 (法国)',
  'de-DE': '德语 (德国)',
  'es-ES': '西班牙语 (西班牙)',
  'ru-RU': '俄语 (俄罗斯)'
}

export const PRESET_VOICES: VoiceMetadata[] = [
  {
    name: 'zh-CN-XiaoxiaoNeural',
    displayName: '晓晓',
    localName: '晓晓',
    locale: 'zh-CN',
    localeName: '中文 (普通话, 简体)',
    gender: 'Female',
    voiceType: 'Neural',
    categories: ['通用助手', '有声读物', '多情感'],
    description: '声音自然流畅、温暖生动，微软旗舰多情感多场景女声',
    avatarColor: '#ec4899',
    styleList: [
      'assistant',
      'chat',
      'customerservice',
      'newscast',
      'affectionate',
      'angry',
      'calm',
      'cheerful',
      'disgruntled',
      'fearful',
      'gentle',
      'lyrical',
      'sad',
      'serious',
      'whispering',
      'poetry-reading'
    ],
    rolePlayList: ['Girl', 'YoungAdultFemale', 'OlderAdultFemale', 'SeniorFemale']
  },
  {
    name: 'zh-CN-YunxiNeural',
    displayName: '云希',
    localName: '云希',
    locale: 'zh-CN',
    localeName: '中文 (普通话, 简体)',
    gender: 'Male',
    voiceType: 'Neural',
    categories: ['影视旁白', '解说名嘴', '短视频爆款'],
    description: '抖音/小红书影视解说顶流音色，富有感染力与剧情张力',
    avatarColor: '#3b82f6',
    styleList: [
      'narration-relaxed',
      'embarrassed',
      'fearful',
      'cheerful',
      'disgruntled',
      'serious',
      'angry',
      'sad',
      'depressed',
      'chat',
      'assistant',
      'newscast'
    ],
    rolePlayList: ['Boy', 'YoungAdultMale', 'OlderAdultMale', 'SeniorMale']
  },
  {
    name: 'zh-CN-YunjianNeural',
    displayName: '云健',
    localName: '云健',
    locale: 'zh-CN',
    localeName: '中文 (普通话, 简体)',
    gender: 'Male',
    voiceType: 'Neural',
    categories: ['体育解说', '激情广告', '纪录片'],
    description: '稳重激昂、穿透力强，适合纪录片解说、体育赛事和快节奏叙事',
    avatarColor: '#6366f1',
    styleList: [
      'sports-commentary',
      'sports-commentary-excited',
      'documentary-narration',
      'narration-relaxed',
      'narration-professional'
    ]
  },
  {
    name: 'zh-CN-XiaoyiNeural',
    displayName: '晓伊',
    localName: '晓伊',
    locale: 'zh-CN',
    localeName: '中文 (普通话, 简体)',
    gender: 'Female',
    voiceType: 'Neural',
    categories: ['有声小说', '抒情诗歌', '温柔治愈'],
    description: '细腻甜美、富有文学意境，特别擅长文学朗读与心灵电台',
    avatarColor: '#f43f5e',
    styleList: ['affectionate', 'angry', 'cheerful', 'disgruntled', 'embarrassed', 'fearful', 'sad']
  },
  {
    name: 'zh-CN-YunyangNeural',
    displayName: '云扬',
    localName: '云扬',
    locale: 'zh-CN',
    localeName: '中文 (普通话, 简体)',
    gender: 'Male',
    voiceType: 'Neural',
    categories: ['新闻专业播报', '高端商务'],
    description: '权威、专业、端庄大气的专业新闻联播主持人声线',
    avatarColor: '#0ea5e9',
    styleList: ['customerservice', 'newscast', 'newscast-casual']
  },
  {
    name: 'zh-CN-XiaomengNeural',
    displayName: '晓梦',
    localName: '晓梦',
    locale: 'zh-CN',
    localeName: '中文 (普通话, 简体)',
    gender: 'Female',
    voiceType: 'Neural',
    categories: ['对话聊天', '直播带货', '客服'],
    description: '亲切灵动、极富销售带动力与互动感染力',
    avatarColor: '#8b5cf6',
    styleList: ['chat', 'livecommercial', 'advertisement-upbeat']
  },
  {
    name: 'zh-CN-XiaochenNeural',
    displayName: '晓辰',
    localName: '晓辰',
    locale: 'zh-CN',
    localeName: '中文 (普通话, 简体)',
    gender: 'Female',
    voiceType: 'Neural',
    categories: ['知性解说', '社科知识'],
    description: '温婉睿智、干练自信，知识博主与科普视频首选女声',
    avatarColor: '#10b981'
  },
  {
    name: 'zh-CN-YunfengNeural',
    displayName: '云枫',
    localName: '云枫',
    locale: 'zh-CN',
    localeName: '中文 (普通话, 简体)',
    gender: 'Male',
    voiceType: 'Neural',
    categories: ['现代都市', '故事长文'],
    description: '沉稳富有磁性，中青年质感男声，叙事耐听度极高',
    avatarColor: '#14b8a6'
  },
  {
    name: 'zh-HK-HiuGaaiNeural',
    displayName: '晓佳 (粤语)',
    localName: '曉佳',
    locale: 'zh-HK',
    localeName: '中文 (粤语, 香港)',
    gender: 'Female',
    voiceType: 'Neural',
    categories: ['粤语播报', '客服助手'],
    description: '地道港式粤语女声，自然标准',
    avatarColor: '#f59e0b'
  },
  {
    name: 'zh-HK-WanLungNeural',
    displayName: '云龙 (粤语)',
    localName: '雲龍',
    locale: 'zh-HK',
    localeName: '中文 (粤语, 香港)',
    gender: 'Male',
    voiceType: 'Neural',
    categories: ['粤语影视', '叙事评述'],
    description: '地道成熟港式男声',
    avatarColor: '#ef4444'
  },
  {
    name: 'zh-TW-HsiaoChenNeural',
    displayName: '晓臻 (台湾)',
    localName: '曉臻',
    locale: 'zh-TW',
    localeName: '中文 (台湾普通话)',
    gender: 'Female',
    voiceType: 'Neural',
    categories: ['温婉女声', '宝岛风情'],
    description: '温柔甜美、语调柔和的台湾普通话女声',
    avatarColor: '#ec4899'
  },
  {
    name: 'en-US-JennyNeural',
    displayName: 'Jenny (English)',
    localName: 'Jenny',
    locale: 'en-US',
    localeName: '英语 (美国)',
    gender: 'Female',
    voiceType: 'Neural',
    categories: ['Fluent English', 'Multistyle', 'Assistant'],
    description: 'Microsoft flagship English multi-style female voice',
    avatarColor: '#38bdf8',
    styleList: ['assistant', 'chat', 'customerservice', 'newscast', 'angry', 'cheerful', 'sad', 'excited', 'friendly', 'whispering']
  },
  {
    name: 'en-US-GuyNeural',
    displayName: 'Guy (English)',
    localName: 'Guy',
    locale: 'en-US',
    localeName: '英语 (美国)',
    gender: 'Male',
    voiceType: 'Neural',
    categories: ['Fluent English', 'Documentary', 'Casual'],
    description: 'Natural, warm and conversational American male voice',
    avatarColor: '#60a5fa',
    styleList: ['newscast', 'angry', 'cheerful', 'sad']
  }
]
